[features]
seeds = false
[programs.localnet]
burn_refund = "622WNfmPwDsWcbTmbURpGHHAokHnD5bdgHYNj6aUE9oo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "devnet"
cluster = "https://frosty-floral-wind.solana-devnet.quiknode.pro/fa3c7dec03be0b5335ff2905b342eedf94ada834/"
wallet = "/home/setmax/.config/solana/devnet.json"
#cluster = "localnet"
#wallet = "/home/setmax/.config/solana/id.json"
#cluster = "http://127.0.0.1:8899"
#wallet = "/home/setmax/.config/solana/localnet.json"

[test]
startup_wait = 5000


[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
